### ISSUE TITLE
Move to PCs4Kids org

### ISSUE THREAD

**Issue by themakshter** [imolorhe/gas#1]
Hey,

I asked on the PCs4Kids slack channel as well, but you might not be using it anymore so here it is: is it okay to move this game under the PCs4Kids org on GitHub? I wanted to convert it into a library to use in the world application and would like to have it all under the same roof if possible. I've invited you to the org and will grant you admin rights as well. 

Thanks for listening, do let me know!

**Comment by imolorhe** [comment]
Okay
